<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'allejo\\socrata\\exceptions\\curlexception' => '/Exceptions/CurlException.php',
                'allejo\\socrata\\exceptions\\httpexception' => '/Exceptions/HttpException.php',
                'allejo\\socrata\\exceptions\\invalidresourceexception' => '/Exceptions/InvalidResourceException.php',
                'allejo\\socrata\\sodaclient' => '/SodaClient.php',
                'allejo\\socrata\\soqlorderdirection' => '/SoqlQuery.php',
                'allejo\\socrata\\soqlquery' => '/SoqlQuery.php',
                'allejo\\socrata\\utilities\\urlquery' => '/Utilities/UrlQuery.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
